title: Scaling Expertise
description: Automation of Security Challenges
author: Tim Schulz
github: https://github.com/automate-tim
about: I'm a security researcher and purple team advocate. Focusing on automation and data driven security testing.
disqus_shortname: scalingexpertise
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/teschulz"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/tim-schulz/"
    - icon: fa-github
      link: "https://github.com/automate-tim"

share:
  twitter_username: teschulz

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://automate-tim.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
